# Generated by Django 4.2.2 on 2024-05-17 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloCliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleBodega',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCliente.producto')),
            ],
        ),
    ]
