# Generated by Django 5.0.1 on 2024-07-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloBodeguero', '0001_initial'),
        ('moduloCliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallebodega',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCliente.producto'),
        ),
    ]
