# Generated by Django 5.0.6 on 2024-06-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCliente', '0002_producto_activo_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='id_categoria',
        ),
    ]
