# Generated by Django 5.0.1 on 2024-06-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCliente', '0002_producto_activo_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/productos/'),
        ),
    ]
# Generated by Django 4.2.2 on 2024-05-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCliente', '0002_producto_activo_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
